---
categories:
- ""
- ""
date: "2020-09-19"
description: IMdB Analysis 
draft: false
image: imdb.jpg
keywords: ""
slug: blog5
title: IMdB Analysis
---

<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />


<p>Image Source: <a href="https://www.amazon.jobs/en/teams/imdb?ref_=ft_jb">Amazon.jobs</a> [Accessed 19 Sept. 2020]</p>
<div id="can-we-estimate-a-movies-box-office-earnings" class="section level1">
<h1>Can we estimate a movie’s box office earnings?</h1>
<div id="analysis-of-movies-in-the-imdb-dataset" class="section level2">
<h2>Analysis of movies in the IMDB dataset</h2>
<p>IMDb (also known as the Internet Movie Database) is an online database, owned by Amazon, of information related to films, television programs, home videos, video games, and streaming content online – including cast, production crew and personal biographies, plot summaries, trivia, ratings, and fan and critical reviews. IMDb has approximately 6.5 million titles (including episodes) and 10.4 million personalities in its database, as well as 83 million registered users.[<a href="https://en.wikipedia.org/wiki/IMDb">1</a>]</p>
<p>I’m sure we all use IMdB to to get information about good movies and it’s a great resource when we are indecisive on which movie to watch. In this analysis, I looked at a dataset which constitutes of only 2961 movies on IMdB. This dataset informs us about some interesting characteristics of movies such as revenue and budget, facebook likes that the cast members received, rating and reviews etc which will help me gain great insights. By the end of this analysis, you will get a sense about whether parameters like the budget, facebook likes etc. have a relationship with the gross earnings of a movie. So let’s look at what we have in our dataframe and begin the analysis!</p>
<pre class="r"><code>#Load dataset using read_csv function and use glimpse to take a look at the dataset.
movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
glimpse(movies)</code></pre>
<pre><code>## Rows: 2,961
## Columns: 11
## $ title               &lt;chr&gt; &quot;Avatar&quot;, &quot;Titanic&quot;, &quot;Jurassic World&quot;, &quot;The Aveng…
## $ genre               &lt;chr&gt; &quot;Action&quot;, &quot;Drama&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;Action&quot;, …
## $ director            &lt;chr&gt; &quot;James Cameron&quot;, &quot;James Cameron&quot;, &quot;Colin Trevorro…
## $ year                &lt;dbl&gt; 2009, 1997, 2015, 2012, 2008, 1999, 1977, 2015, 2…
## $ duration            &lt;dbl&gt; 178, 194, 124, 173, 152, 136, 125, 141, 164, 93, …
## $ gross               &lt;dbl&gt; 7.61e+08, 6.59e+08, 6.52e+08, 6.23e+08, 5.33e+08,…
## $ budget              &lt;dbl&gt; 2.37e+08, 2.00e+08, 1.50e+08, 2.20e+08, 1.85e+08,…
## $ cast_facebook_likes &lt;dbl&gt; 4834, 45223, 8458, 87697, 57802, 37723, 13485, 92…
## $ votes               &lt;dbl&gt; 886204, 793059, 418214, 995415, 1676169, 534658, …
## $ reviews             &lt;dbl&gt; 3777, 2843, 1934, 2425, 5312, 3917, 1752, 1752, 3…
## $ rating              &lt;dbl&gt; 7.9, 7.7, 7.0, 8.1, 9.0, 6.5, 8.7, 7.5, 8.5, 7.2,…</code></pre>
<p>Now let’s see what we can actually learn from this dataframe!</p>
<p>Before everything else, I perform data cleaning and data wrangling to ensure that I’m using the most optimized subset of the dataset to structure my hypothesis.</p>
<pre class="r"><code>#Skim function provides a broad overview of the dataframe for us whereas duplicated shows us if there are any duplicated values in the dataframe.
skim(movies)</code></pre>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
(#tab:gross_on_budget)Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
movies
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
2961
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
11
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
8
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
title
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
83
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2907
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
genre
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
director
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1366
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
year
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2.00e+03
</td>
<td style="text-align:right;">
9.95e+00
</td>
<td style="text-align:right;">
1920.0
</td>
<td style="text-align:right;">
2.00e+03
</td>
<td style="text-align:right;">
2.00e+03
</td>
<td style="text-align:right;">
2.01e+03
</td>
<td style="text-align:right;">
2.02e+03
</td>
<td style="text-align:left;">
▁▁▁▂▇
</td>
</tr>
<tr>
<td style="text-align:left;">
duration
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.10e+02
</td>
<td style="text-align:right;">
2.22e+01
</td>
<td style="text-align:right;">
37.0
</td>
<td style="text-align:right;">
9.50e+01
</td>
<td style="text-align:right;">
1.06e+02
</td>
<td style="text-align:right;">
1.19e+02
</td>
<td style="text-align:right;">
3.30e+02
</td>
<td style="text-align:left;">
▃▇▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
gross
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5.81e+07
</td>
<td style="text-align:right;">
7.25e+07
</td>
<td style="text-align:right;">
703.0
</td>
<td style="text-align:right;">
1.23e+07
</td>
<td style="text-align:right;">
3.47e+07
</td>
<td style="text-align:right;">
7.56e+07
</td>
<td style="text-align:right;">
7.61e+08
</td>
<td style="text-align:left;">
▇▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
budget
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.06e+07
</td>
<td style="text-align:right;">
4.37e+07
</td>
<td style="text-align:right;">
218.0
</td>
<td style="text-align:right;">
1.10e+07
</td>
<td style="text-align:right;">
2.60e+07
</td>
<td style="text-align:right;">
5.50e+07
</td>
<td style="text-align:right;">
3.00e+08
</td>
<td style="text-align:left;">
▇▂▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
cast_facebook_likes
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.24e+04
</td>
<td style="text-align:right;">
2.05e+04
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2.24e+03
</td>
<td style="text-align:right;">
4.60e+03
</td>
<td style="text-align:right;">
1.69e+04
</td>
<td style="text-align:right;">
6.57e+05
</td>
<td style="text-align:left;">
▇▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
votes
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.09e+05
</td>
<td style="text-align:right;">
1.58e+05
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
1.99e+04
</td>
<td style="text-align:right;">
5.57e+04
</td>
<td style="text-align:right;">
1.33e+05
</td>
<td style="text-align:right;">
1.69e+06
</td>
<td style="text-align:left;">
▇▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
reviews
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5.03e+02
</td>
<td style="text-align:right;">
4.94e+02
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
1.99e+02
</td>
<td style="text-align:right;">
3.64e+02
</td>
<td style="text-align:right;">
6.31e+02
</td>
<td style="text-align:right;">
5.31e+03
</td>
<td style="text-align:left;">
▇▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
rating
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
6.39e+00
</td>
<td style="text-align:right;">
1.05e+00
</td>
<td style="text-align:right;">
1.6
</td>
<td style="text-align:right;">
5.80e+00
</td>
<td style="text-align:right;">
6.50e+00
</td>
<td style="text-align:right;">
7.10e+00
</td>
<td style="text-align:right;">
9.30e+00
</td>
<td style="text-align:left;">
▁▁▆▇▁
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>sum(duplicated(movies))</code></pre>
<pre><code>## [1] 0</code></pre>
<p>You can see that there are no missing values in any of the attributes. If there were any duplicate entries then they would be marked true in <code>duplicate(movies)</code>. The sum <code>sum(duplicated(movies))</code> gives us 0. And as we know that true means 1, we do not have any duplicate entries.</p>
<p>But wait a minute!!! There is something fishy definitely going on here behind the scenes. You can see that there are 2,961 records in this dataframe but there are only 2907 unique titles?! We now need to check whether there is actually some fishy title business or not.</p>
<pre class="r"><code>#We will look at only the movie titles now whether they have duplicates or not.
sum(duplicated(movies$title))</code></pre>
<pre><code>## [1] 54</code></pre>
<pre class="r"><code>#Let us take a look at all the duplicated movies
movies %&gt;%
  #We will filter the movies which have duplicates
  filter(duplicated(movies$title)) %&gt;% 
  #We will arrange them by title in an alphabetical order
  arrange(title) %&gt;% 
  #We will only display 5 of the duplicates
  top_n(5) %&gt;%
  #We should remove the duplicate movies %&gt;%
  kable(caption=&quot;Duplicated Movies&quot;, col.names=c(&quot;Movie Title&quot;, &quot;Genre&quot;, &quot;Director&quot;, &quot;Year&quot;, &quot;Duration&quot;, &quot;Gross earnings&quot;, &quot;Budget&quot;, &quot;Facebook likes&quot;, &quot;Votes&quot;, &quot;Reviews&quot;, &quot;Rating&quot;)) %&gt;% 
  #Why not add some styling? 
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:movies_title_duplicated)Duplicated Movies
</caption>
<thead>
<tr>
<th style="text-align:left;">
Movie Title
</th>
<th style="text-align:left;">
Genre
</th>
<th style="text-align:left;">
Director
</th>
<th style="text-align:right;">
Year
</th>
<th style="text-align:right;">
Duration
</th>
<th style="text-align:right;">
Gross earnings
</th>
<th style="text-align:right;">
Budget
</th>
<th style="text-align:right;">
Facebook likes
</th>
<th style="text-align:right;">
Votes
</th>
<th style="text-align:right;">
Reviews
</th>
<th style="text-align:right;">
Rating
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A Nightmare on Elm Street
</td>
<td style="text-align:left;">
Horror
</td>
<td style="text-align:left;">
Wes Craven
</td>
<td style="text-align:right;">
1984
</td>
<td style="text-align:right;">
101
</td>
<td style="text-align:right;">
2.65e+07
</td>
<td style="text-align:right;">
1800000
</td>
<td style="text-align:right;">
42918
</td>
<td style="text-align:right;">
149293
</td>
<td style="text-align:right;">
924
</td>
<td style="text-align:right;">
7.5
</td>
</tr>
<tr>
<td style="text-align:left;">
Glory
</td>
<td style="text-align:left;">
Drama
</td>
<td style="text-align:left;">
Edward Zwick
</td>
<td style="text-align:right;">
1989
</td>
<td style="text-align:right;">
122
</td>
<td style="text-align:right;">
2.68e+07
</td>
<td style="text-align:right;">
18000000
</td>
<td style="text-align:right;">
32930
</td>
<td style="text-align:right;">
101889
</td>
<td style="text-align:right;">
425
</td>
<td style="text-align:right;">
7.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Halloween
</td>
<td style="text-align:left;">
Horror
</td>
<td style="text-align:left;">
John Carpenter
</td>
<td style="text-align:right;">
1978
</td>
<td style="text-align:right;">
101
</td>
<td style="text-align:right;">
4.70e+07
</td>
<td style="text-align:right;">
300000
</td>
<td style="text-align:right;">
4400
</td>
<td style="text-align:right;">
157863
</td>
<td style="text-align:right;">
1509
</td>
<td style="text-align:right;">
7.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Juno
</td>
<td style="text-align:left;">
Comedy
</td>
<td style="text-align:left;">
Jason Reitman
</td>
<td style="text-align:right;">
2007
</td>
<td style="text-align:right;">
96
</td>
<td style="text-align:right;">
1.43e+08
</td>
<td style="text-align:right;">
7500000
</td>
<td style="text-align:right;">
28817
</td>
<td style="text-align:right;">
414345
</td>
<td style="text-align:right;">
1268
</td>
<td style="text-align:right;">
7.5
</td>
</tr>
<tr>
<td style="text-align:left;">
The Texas Chain Saw Massacre
</td>
<td style="text-align:left;">
Horror
</td>
<td style="text-align:left;">
Tobe Hooper
</td>
<td style="text-align:right;">
1974
</td>
<td style="text-align:right;">
88
</td>
<td style="text-align:right;">
3.09e+07
</td>
<td style="text-align:right;">
83532
</td>
<td style="text-align:right;">
1094
</td>
<td style="text-align:right;">
96411
</td>
<td style="text-align:right;">
1103
</td>
<td style="text-align:right;">
7.5
</td>
</tr>
</tbody>
</table>
<p>You can see that there are 54 movies having the same title. The skim function also said that there are 2907 unique titles and 2961 total movies in the list. So we have 54 again. When we filtered the duplicate movie titles, we saw the top 5 of them that appear twice in our dataframe.</p>
<p>Now let me actually remove all of these duplicates! The duplicates differed in either the number of reviews or the number of votes and therefore could not be spotted if looking at only whether there exist duplicates or not in the dataframe.</p>
<p>Now that we have done the initial data cleaning process and 70% of our jobs as Data Scientists, let me take a look at all the movies present in this database and try to understand how many movies are contained for each genre. So, I will construct a table with the count of movies by genre, ranked in descending order. Now that our data is clean, I need to start our exploration process (as elaborately put by the IICE methodology).</p>
<pre class="r"><code># This gives us a table which shows that Comedy, Action and Drama genres have the most number of movies in the database.

movies %&gt;% 
  #We will group the movies by genre
  group_by(genre) %&gt;% 
  #Now we count the number of movies per genre and rank them in descending order
  count(sort=TRUE) %&gt;% 
  #We add a title to the table and give names to its columns.
  kable(caption=&quot;Number of movies per genre&quot;, col.names=c(&quot;Genre&quot;, &quot;Number of movies&quot;)) %&gt;% 
  #Why not add some styling?
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:movies_by_genre)Number of movies per genre
</caption>
<thead>
<tr>
<th style="text-align:left;">
Genre
</th>
<th style="text-align:right;">
Number of movies
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Comedy
</td>
<td style="text-align:right;">
844
</td>
</tr>
<tr>
<td style="text-align:left;">
Action
</td>
<td style="text-align:right;">
719
</td>
</tr>
<tr>
<td style="text-align:left;">
Drama
</td>
<td style="text-align:right;">
484
</td>
</tr>
<tr>
<td style="text-align:left;">
Adventure
</td>
<td style="text-align:right;">
281
</td>
</tr>
<tr>
<td style="text-align:left;">
Crime
</td>
<td style="text-align:right;">
198
</td>
</tr>
<tr>
<td style="text-align:left;">
Biography
</td>
<td style="text-align:right;">
135
</td>
</tr>
<tr>
<td style="text-align:left;">
Horror
</td>
<td style="text-align:right;">
128
</td>
</tr>
<tr>
<td style="text-align:left;">
Animation
</td>
<td style="text-align:right;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
Fantasy
</td>
<td style="text-align:right;">
26
</td>
</tr>
<tr>
<td style="text-align:left;">
Documentary
</td>
<td style="text-align:right;">
25
</td>
</tr>
<tr>
<td style="text-align:left;">
Mystery
</td>
<td style="text-align:right;">
15
</td>
</tr>
<tr>
<td style="text-align:left;">
Sci-Fi
</td>
<td style="text-align:right;">
7
</td>
</tr>
<tr>
<td style="text-align:left;">
Family
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
Musical
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Romance
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Western
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Thriller
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<p>We can see that this database actually contains a majority of Comedy, Action, Drama, Adventure, Crime, Biography, and Horror movies.</p>
<p>In the IMDB Dataset, there exist some genres that have lesser than 10 observations in them. Most of my analysis in this segment is centered on finding the correlations between genres and several different attributes such as average ratings, gross budget, return on investment etc. Most of these genre classes contain more than 10 values but there are 6 classes which contain less than 10 values.</p>
<p>Now, I will look at the average gross earnings and budget by genre plot. Using this, I will also calculate the return on budget that a movie made at the box office for each dollar.
This is going to be really interesting because this will allow me to see if there is indeed a direct correlation between a movie’s budget and its return!</p>
<pre class="r"><code>movies %&gt;% 
  #We will group movies by genre
  group_by(genre) %&gt;% 
  #We will calculate the average gross earning and budget in millions and turn these observations into a single data point per genre.
  summarize(avg_gross = mean(gross)/1000000, 
            avg_budget= mean(budget)/1000000 ) %&gt;% 
  #We will add another column named return_on_budget and calculate it.
  mutate(return_on_budget = 100* (avg_gross - avg_budget) / avg_budget) %&gt;% 
  #Now, arrange it by return on budget in descending order
  arrange(desc(return_on_budget)) %&gt;% 
  #Again, add names to the table and columns
  kable(position=&quot;center&quot;, caption=&quot;Average USD gross earning, average USD budget and return on budget per genre&quot;, col.names=c(&quot;Genre&quot;, &quot;Average gross earning(m)&quot;, &quot;Average budget(m)&quot;, &quot;Return on budget(%)&quot;)) %&gt;% 
  #Add some styling to the table
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:return_on_budget)Average USD gross earning, average USD budget and return on budget per genre
</caption>
<thead>
<tr>
<th style="text-align:left;">
Genre
</th>
<th style="text-align:right;">
Average gross earning(m)
</th>
<th style="text-align:right;">
Average budget(m)
</th>
<th style="text-align:right;">
Return on budget(%)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Musical
</td>
<td style="text-align:right;">
92.084
</td>
<td style="text-align:right;">
3.19
</td>
<td style="text-align:right;">
2787.1
</td>
</tr>
<tr>
<td style="text-align:left;">
Family
</td>
<td style="text-align:right;">
149.160
</td>
<td style="text-align:right;">
14.83
</td>
<td style="text-align:right;">
905.6
</td>
</tr>
<tr>
<td style="text-align:left;">
Western
</td>
<td style="text-align:right;">
20.822
</td>
<td style="text-align:right;">
3.46
</td>
<td style="text-align:right;">
500.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Documentary
</td>
<td style="text-align:right;">
17.354
</td>
<td style="text-align:right;">
5.89
</td>
<td style="text-align:right;">
194.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Horror
</td>
<td style="text-align:right;">
37.782
</td>
<td style="text-align:right;">
13.80
</td>
<td style="text-align:right;">
173.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Fantasy
</td>
<td style="text-align:right;">
41.903
</td>
<td style="text-align:right;">
18.48
</td>
<td style="text-align:right;">
126.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Comedy
</td>
<td style="text-align:right;">
42.488
</td>
<td style="text-align:right;">
24.46
</td>
<td style="text-align:right;">
73.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Mystery
</td>
<td style="text-align:right;">
69.117
</td>
<td style="text-align:right;">
41.50
</td>
<td style="text-align:right;">
66.5
</td>
</tr>
<tr>
<td style="text-align:left;">
Animation
</td>
<td style="text-align:right;">
98.434
</td>
<td style="text-align:right;">
61.70
</td>
<td style="text-align:right;">
59.5
</td>
</tr>
<tr>
<td style="text-align:left;">
Biography
</td>
<td style="text-align:right;">
45.202
</td>
<td style="text-align:right;">
28.54
</td>
<td style="text-align:right;">
58.4
</td>
</tr>
<tr>
<td style="text-align:left;">
Adventure
</td>
<td style="text-align:right;">
94.350
</td>
<td style="text-align:right;">
64.69
</td>
<td style="text-align:right;">
45.8
</td>
</tr>
<tr>
<td style="text-align:left;">
Drama
</td>
<td style="text-align:right;">
36.755
</td>
<td style="text-align:right;">
25.83
</td>
<td style="text-align:right;">
42.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Crime
</td>
<td style="text-align:right;">
37.602
</td>
<td style="text-align:right;">
26.53
</td>
<td style="text-align:right;">
41.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Romance
</td>
<td style="text-align:right;">
31.265
</td>
<td style="text-align:right;">
25.11
</td>
<td style="text-align:right;">
24.5
</td>
</tr>
<tr>
<td style="text-align:left;">
Action
</td>
<td style="text-align:right;">
86.270
</td>
<td style="text-align:right;">
70.78
</td>
<td style="text-align:right;">
21.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Sci-Fi
</td>
<td style="text-align:right;">
29.788
</td>
<td style="text-align:right;">
27.61
</td>
<td style="text-align:right;">
7.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Thriller
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.30
</td>
<td style="text-align:right;">
-99.2
</td>
</tr>
</tbody>
</table>
<p>At first glance at this plot, I thought about entering into the Musical industry! The average return on investment is nearly 27 times the initial budget which is insane! However, I remembered that there are only two Musical movies in this database unfortunately, so it’s too little to predict an accurate return on our investment since I clearly don’t have enough data.</p>
<p>Now, let’s produce a table that shows the top 15 directors who have created the highest gross revenue in the box office. I will also show the mean, median and standard deviation per director. The box office is one of those places where the amount of money earned is directly dependent upon the people reached. So, now, I will try to analyse the list of directors who have touched the maximum number of lives through their movies!</p>
<pre class="r"><code>movies %&gt;% 
  #We group movies by director
  group_by(director) %&gt;% 
  #We will calculate the total gross earning in billions and mean, median and standard deviation in millions and summarize them per director.
  summarize(sum_gross=sum(gross)/1000000,   
            mean = mean(gross)/1000000,               
            median = median(gross)/1000000,
            sd = sd(gross)/1000000 ) %&gt;% 
  #We will arrange them by total gross earnings in descending order
  arrange(desc(sum_gross)) %&gt;%   
  #We need to show only the top 15 directors
  head(15) %&gt;% 
  #Again, add names to the table and columns
  kable(caption=&quot;Top 15 directors by highest revenue in USD&quot;, col.names=c(&quot;Director&quot;, &quot;Total gross Earning(m)&quot;, &quot;Mean(m)&quot;, &quot;Median(m)&quot;, &quot;SD(m)&quot;)) %&gt;% 
  #Add some styling to the table
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:gross_on_fblikes)Top 15 directors by highest revenue in USD
</caption>
<thead>
<tr>
<th style="text-align:left;">
Director
</th>
<th style="text-align:right;">
Total gross Earning(m)
</th>
<th style="text-align:right;">
Mean(m)
</th>
<th style="text-align:right;">
Median(m)
</th>
<th style="text-align:right;">
SD(m)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Steven Spielberg
</td>
<td style="text-align:right;">
4014
</td>
<td style="text-align:right;">
174.5
</td>
<td style="text-align:right;">
164.4
</td>
<td style="text-align:right;">
101.4
</td>
</tr>
<tr>
<td style="text-align:left;">
Michael Bay
</td>
<td style="text-align:right;">
2195
</td>
<td style="text-align:right;">
183.0
</td>
<td style="text-align:right;">
168.5
</td>
<td style="text-align:right;">
125.8
</td>
</tr>
<tr>
<td style="text-align:left;">
James Cameron
</td>
<td style="text-align:right;">
1910
</td>
<td style="text-align:right;">
318.3
</td>
<td style="text-align:right;">
175.6
</td>
<td style="text-align:right;">
309.2
</td>
</tr>
<tr>
<td style="text-align:left;">
Christopher Nolan
</td>
<td style="text-align:right;">
1813
</td>
<td style="text-align:right;">
226.7
</td>
<td style="text-align:right;">
196.7
</td>
<td style="text-align:right;">
187.2
</td>
</tr>
<tr>
<td style="text-align:left;">
George Lucas
</td>
<td style="text-align:right;">
1741
</td>
<td style="text-align:right;">
348.3
</td>
<td style="text-align:right;">
380.3
</td>
<td style="text-align:right;">
146.2
</td>
</tr>
<tr>
<td style="text-align:left;">
Robert Zemeckis
</td>
<td style="text-align:right;">
1619
</td>
<td style="text-align:right;">
124.6
</td>
<td style="text-align:right;">
100.9
</td>
<td style="text-align:right;">
91.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Tim Burton
</td>
<td style="text-align:right;">
1557
</td>
<td style="text-align:right;">
111.2
</td>
<td style="text-align:right;">
69.8
</td>
<td style="text-align:right;">
99.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Sam Raimi
</td>
<td style="text-align:right;">
1443
</td>
<td style="text-align:right;">
180.4
</td>
<td style="text-align:right;">
138.5
</td>
<td style="text-align:right;">
174.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Clint Eastwood
</td>
<td style="text-align:right;">
1378
</td>
<td style="text-align:right;">
72.5
</td>
<td style="text-align:right;">
46.7
</td>
<td style="text-align:right;">
75.5
</td>
</tr>
<tr>
<td style="text-align:left;">
Francis Lawrence
</td>
<td style="text-align:right;">
1359
</td>
<td style="text-align:right;">
271.7
</td>
<td style="text-align:right;">
281.7
</td>
<td style="text-align:right;">
135.4
</td>
</tr>
<tr>
<td style="text-align:left;">
Ron Howard
</td>
<td style="text-align:right;">
1336
</td>
<td style="text-align:right;">
111.3
</td>
<td style="text-align:right;">
101.6
</td>
<td style="text-align:right;">
81.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Gore Verbinski
</td>
<td style="text-align:right;">
1330
</td>
<td style="text-align:right;">
189.9
</td>
<td style="text-align:right;">
123.2
</td>
<td style="text-align:right;">
154.5
</td>
</tr>
<tr>
<td style="text-align:left;">
Andrew Adamson
</td>
<td style="text-align:right;">
1137
</td>
<td style="text-align:right;">
284.4
</td>
<td style="text-align:right;">
279.7
</td>
<td style="text-align:right;">
120.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Shawn Levy
</td>
<td style="text-align:right;">
1130
</td>
<td style="text-align:right;">
102.7
</td>
<td style="text-align:right;">
85.5
</td>
<td style="text-align:right;">
65.5
</td>
</tr>
<tr>
<td style="text-align:left;">
Ridley Scott
</td>
<td style="text-align:right;">
1129
</td>
<td style="text-align:right;">
80.6
</td>
<td style="text-align:right;">
47.8
</td>
<td style="text-align:right;">
68.8
</td>
</tr>
</tbody>
</table>
<p>Okay so the data I’m dealing with is definitely accurate since these 15 directors are absolute geniuses.</p>
<p>Now, I come to the part to learn what the audience think about these movies. We will produce a table that describes how ratings are distributed by genre. I know that money is definitely one way an audience shows love to the movie, but a movie can actually perform incredibly at the box office even if it isn’t a great movie - it all depends upon how good the marketing geniuses behind the film’s promotion are good at their jobs. In today’s day and age, there exist very few people who watch a movie without checking for its review in IMDB, so now let’s see how the ratings of movies are distributed by their genre. After all, we still do want to confirm which movies to make as making a movie that earns money but doesn’t get us the people’s love isn’t really fun, is it?</p>
<pre class="r"><code>movies %&gt;% 
  #Group movies by genre
  group_by(genre) %&gt;% 
  #Summarize mean, min, max, sd of ratings per genre
  summarise(mean= mean(rating), 
            min=min(rating),
            max=max(rating),
            sd=sd(rating)) %&gt;% 
  #Just arrange them to make the table more readable
  arrange(desc(mean)) %&gt;%
  #Add table title  and column names
  kable(caption=&quot;Distribution of ratings by genre&quot;, col.names = c(&quot;Genre&quot;, &quot;Mean&quot;, &quot;Min&quot;, &quot;Max&quot;, &quot;SD&quot;)) %&gt;% 
  #Add some styling to the table
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:ratings_genre_dataframe)Distribution of ratings by genre
</caption>
<thead>
<tr>
<th style="text-align:left;">
Genre
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
Min
</th>
<th style="text-align:right;">
Max
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Biography
</td>
<td style="text-align:right;">
7.11
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
8.9
</td>
<td style="text-align:right;">
0.760
</td>
</tr>
<tr>
<td style="text-align:left;">
Crime
</td>
<td style="text-align:right;">
6.92
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
9.3
</td>
<td style="text-align:right;">
0.853
</td>
</tr>
<tr>
<td style="text-align:left;">
Mystery
</td>
<td style="text-align:right;">
6.84
</td>
<td style="text-align:right;">
4.6
</td>
<td style="text-align:right;">
8.5
</td>
<td style="text-align:right;">
0.910
</td>
</tr>
<tr>
<td style="text-align:left;">
Musical
</td>
<td style="text-align:right;">
6.75
</td>
<td style="text-align:right;">
6.3
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
0.636
</td>
</tr>
<tr>
<td style="text-align:left;">
Drama
</td>
<td style="text-align:right;">
6.74
</td>
<td style="text-align:right;">
2.1
</td>
<td style="text-align:right;">
8.8
</td>
<td style="text-align:right;">
0.915
</td>
</tr>
<tr>
<td style="text-align:left;">
Documentary
</td>
<td style="text-align:right;">
6.66
</td>
<td style="text-align:right;">
1.6
</td>
<td style="text-align:right;">
8.5
</td>
<td style="text-align:right;">
1.767
</td>
</tr>
<tr>
<td style="text-align:left;">
Sci-Fi
</td>
<td style="text-align:right;">
6.66
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
8.2
</td>
<td style="text-align:right;">
1.094
</td>
</tr>
<tr>
<td style="text-align:left;">
Animation
</td>
<td style="text-align:right;">
6.65
</td>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
8.0
</td>
<td style="text-align:right;">
0.968
</td>
</tr>
<tr>
<td style="text-align:left;">
Romance
</td>
<td style="text-align:right;">
6.65
</td>
<td style="text-align:right;">
6.2
</td>
<td style="text-align:right;">
7.1
</td>
<td style="text-align:right;">
0.636
</td>
</tr>
<tr>
<td style="text-align:left;">
Adventure
</td>
<td style="text-align:right;">
6.51
</td>
<td style="text-align:right;">
2.3
</td>
<td style="text-align:right;">
8.6
</td>
<td style="text-align:right;">
1.106
</td>
</tr>
<tr>
<td style="text-align:left;">
Family
</td>
<td style="text-align:right;">
6.50
</td>
<td style="text-align:right;">
5.7
</td>
<td style="text-align:right;">
7.9
</td>
<td style="text-align:right;">
1.217
</td>
</tr>
<tr>
<td style="text-align:left;">
Action
</td>
<td style="text-align:right;">
6.23
</td>
<td style="text-align:right;">
2.1
</td>
<td style="text-align:right;">
9.0
</td>
<td style="text-align:right;">
1.039
</td>
</tr>
<tr>
<td style="text-align:left;">
Comedy
</td>
<td style="text-align:right;">
6.11
</td>
<td style="text-align:right;">
1.9
</td>
<td style="text-align:right;">
8.8
</td>
<td style="text-align:right;">
1.024
</td>
</tr>
<tr>
<td style="text-align:left;">
Fantasy
</td>
<td style="text-align:right;">
6.08
</td>
<td style="text-align:right;">
4.3
</td>
<td style="text-align:right;">
7.9
</td>
<td style="text-align:right;">
0.953
</td>
</tr>
<tr>
<td style="text-align:left;">
Horror
</td>
<td style="text-align:right;">
5.79
</td>
<td style="text-align:right;">
3.6
</td>
<td style="text-align:right;">
8.5
</td>
<td style="text-align:right;">
0.987
</td>
</tr>
<tr>
<td style="text-align:left;">
Western
</td>
<td style="text-align:right;">
5.70
</td>
<td style="text-align:right;">
4.1
</td>
<td style="text-align:right;">
7.3
</td>
<td style="text-align:right;">
2.263
</td>
</tr>
<tr>
<td style="text-align:left;">
Thriller
</td>
<td style="text-align:right;">
4.80
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
<p>Now, we can see that the audience is particularly fond of watching biographies, crime, mystery, and drama movies.</p>
<pre class="r"><code>  #Plot a histogram using movies dataframe, x axis shows rating
  ggplot(data = movies, mapping = aes(x = rating) ) +
  #Choose white for color of bin lines
      geom_histogram(color=&quot;white&quot;) +
  #Add title for the plot and x and y axis
      labs(title=&quot;Distribution of ratings&quot;, x=&quot;Rating&quot;, y=&quot;Number of movies&quot;) +
  #Choose the theme minimal for the plot styling
      theme_minimal() </code></pre>
<p><img src="/blogs/blog5_files/figure-html/ratings_genre_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>This histogram clearly shows that most movies tend to obtain IMDB ratings between 5 and 7.5.</p>
<p>Now, I will examine the relationships between some variables for the next few analysis. Firstly, I will produce a scatter plot to see whether the number of facebook likes that the cast has received is likely to be a good predictor of how much money a movie will make at the box office.</p>
<pre class="r"><code>#We will plot a scatterplot with movies data, we will map the number of facebook likes that the cast received in thousands on the x axis and gross earnings in millions on the y axis.
ggplot(data = movies, mapping = aes(x=cast_facebook_likes/1000, y=gross/1000000)) +
      geom_point() + 
      #We will add a title to the plot and to the x and y axis.
      labs(title=&quot;Relationship between gross revenue and facebook likes of a movie&quot;, x=&quot;Number of facebook likes(k)&quot;, y=&quot;Gross earning(m USD)&quot;) +
      #We will choose theme minimal for the plot styling.
      theme_minimal()   </code></pre>
<p><img src="/blogs/blog5_files/figure-html/gross_on_ggplot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>This graph depicts that there doesn’t exist any significant correlation between the Number of Facebook Likes and Gross Earnings. But we aren’t 100% sure if this is actually the case at this point, let us try to rearrange our graph to see if this actually holds true!</p>
<pre class="r"><code># We will create another version of this scatter plot
ggplot(data = movies, aes(x=cast_facebook_likes/1000, y=gross/1000000)) + 
  # We will set the opacity of the points to 0.2
  geom_point(alpha = 0.3) + 
  # We will try to depict the smoothing line
  geom_smooth() + 
  # We will try to get a logarithmic scale for both these axis
  scale_y_log10() + 
  scale_x_log10() +
  # Finally we will label our plot again
  labs(title = &quot;box office earnings on number of facebook likes&quot;,
       subtitle = &quot;logarithmic scales&quot;,
       x = &quot;Number of facebook likes(k)&quot;,
       y = &quot;Gross earning(m USD)&quot;)</code></pre>
<p><img src="/blogs/blog5_files/figure-html/gross_on_ggplot2-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>From this plot, we can actually see that there exists a correlation between the gross earnings and the Number of Facebook Likes! So this means that while producing a movie, we should definitely consider allocating some budget to marketing the movie on Facebook through the best possible way!</p>
<p>Now let me take a look at a scatter plot between the budget of the film and its gross revenues at the box office. We want to see if we really do need to spend a lot of money out of our pockets while creating the film to ensure that it performs well at the box office!</p>
<pre class="r"><code>#We will plot a scatterplot with movies data, we will map the gross earnings on the x axis and budget on the y axis, both are in millions
ggplot(data = movies, mapping = aes(x=gross/1000000, y=budget/1000000)) +
      geom_point() + 
#We will draw a line of best fit to better understand the trend
      geom_smooth() +
#We will add titles
      labs(title=&quot;Relationship between gross revenue and budget of a movie&quot;, x=&quot;Gross revenue(m USD)&quot;, y=&quot;Budget(m USD)&quot;) +
#Choose theme minimal for plot syling
      theme_minimal()       </code></pre>
<p><img src="/blogs/blog5_files/figure-html/gross_budget_scatter-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>There exists a clear correlation between budget and gross that can be modeled by the polynomial plot, therefore it is likely that budget is a good predictor of how much money a movie will make at the box office. This means that while making our own movies, we will need to guarantee that we have at least a respectable few millions to make the movie.</p>
<p>Next, I will take a look at the scatterplot faceted by genre to see whether IMDB ratings are likely to be a good predictor of how much money a movie will make at the box office. Let’s see if there is anything strange in this dataset.</p>
<pre class="r"><code>#We will produce a scatterplot with movies data, we will map IMDb ratings on the x axis and gross earnings in millions on the y axis.
ggplot(data = movies, mapping = aes(x=rating, y=gross/1000000)) +
      geom_point(alpha=0.2) +
      #We will produce a plot for each genre
      facet_wrap(~genre) +
      #Adding a fitting line using the geom_smooth function
      geom_smooth() +
      #Add title for plot and axis
      labs(title=&quot;Relationship between gross revenue and rating by genre&quot;, x=&quot;Rating&quot;, y=&quot;Gross revenue(m USD)&quot;) </code></pre>
<p><img src="/blogs/blog5_files/figure-html/gross_on_rating-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Action and Adventure movies with high IMDb ratings have gained better box office revenue so you might think ratings are a good predictor of the box office earnings. But this trend changes according to the genre, we see that for example gross revenue for Comedy, Crime and Drama genres are not sensitive to rating and follow a straight line. And finally, for Musical, Romance and Western movies we don’t have much data to make an inference. Therefore, IMDB ratings are not always an indicator of how much a movie will make.</p>
<p>At the end, we are able to ascertain a few important points:</p>
<ul>
<li>There exists a positive correlation between the Gross Earnings of a movie and the number of Facebook likes obtained; this means that it is a good idea to market the movie on Facebook extensively pre-release.</li>
<li>There exists a positive correlation between a film’s budget to its gross earnings at the post office; so while looking at producing a movie, it is generally a good idea to put in some money.</li>
<li>The top 15 Directors are (undoubtably) Steven Spielberg, Michael Bay, James Cameron, Christopher Nolan, George Lucas, Robert Zemeckis, Tim Burton, Sam Raimi, Clint Eastwood, Francis Lawrence, Ron Howard, Gore Verbinski, Andrew Adamson, Shawn Levy, and Ridley Scott.</li>
</ul>
<p><strong>References</strong></p>
<p>[1] <a href="https://en.wikipedia.org/wiki/IMDb" class="uri">https://en.wikipedia.org/wiki/IMDb</a> [Accessed 19 Sept. 2020]</p>
</div>
</div>
